" Name:         Dromad
" Description:  Color scheme based on Caves of Qud’s palette.
" Author:       N. G. Scheurich <nick@scheurich.me>
" Maintainer:   N. G. Scheurich <nick@scheurich.me>
" Website:      https://github.com/ngscheurich/dromad-vim
" License:      MIT
" Last Updated: Fri Aug 14 10:53:34 2020

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'dromad'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link EndOfBuffer NonText
hi! link Exception Statement
hi! link Float Number
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#0F3B3A', '#D74200', '#00C420', '#CFC041',
        \ '#0096FF', '#DA5BD6', '#77BFCF', '#FFFFFF', '#0F3B3A', '#D74200',
        \ '#00C420', '#CFC041', '#0096FF', '#DA5BD6', '#77BFCF', '#FFFFFF']
  hi Normal guifg=#B1C9C3 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#155352 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#B1C9C3 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#155352 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=bold cterm=bold
  hi DiffAdd guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#E99F10 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#B1C9C3 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#B1C9C3 guibg=#155352 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#155352 guibg=#B1C9C3 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#FFFFFF guibg=#155352 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#FFFFFF guibg=#0F3B3A guisp=#A64A2E gui=NONE cterm=NONE
  hi SpellCap guifg=#FFFFFF guibg=#0F3B3A guisp=#0048BD gui=NONE cterm=NONE
  hi SpellLocal guifg=#FFFFFF guibg=#0F3B3A guisp=#B154CF gui=NONE cterm=NONE
  hi SpellRare guifg=#FFFFFF guibg=#0F3B3A guisp=#40A4B9 gui=reverse cterm=reverse
  hi StatusLine guifg=#0F3B3A guibg=#B1C9C3 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#0F3B3A guibg=#155352 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#155352 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#FFFFFF guibg=#155352 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#B1C9C3 guibg=#0F3B3A guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#98875F guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#A64A2E guibg=#0F3B3A guisp=NONE gui=bold,underline cterm=bold,underline
  hi Identifier guifg=#0096FF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#B1C9C3 guibg=#0F3B3A guisp=NONE gui=bold cterm=bold
  hi PreProc guifg=#77BFCF guibg=#0F3B3A guisp=NONE gui=bold cterm=bold
  hi Special guifg=#D74200 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#40A4B9 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#E99F10 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#CFC041 guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#0F3B3A guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#FFFFFF guibg=#0F3B3A guisp=NONE gui=bold cterm=bold
  hi elixirAtom guifg=#00C420 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirFunctionCall guifg=#77BFCF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirOperator guifg=#0096FF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirAlias guifg=#FFFFFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirTupleDelimiter guifg=#DA5BD6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi elixirStringDelimiter guifg=#98875F guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimcontinue guifg=#DA5BD6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimparensep guifg=#DA5BD6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimsep guifg=#DA5BD6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=152 ctermbg=23 cterm=NONE
  if !has('patch-8.0.0616') " Fix for Vim bug
    set background=dark
  endif
  hi Terminal ctermfg=231 ctermbg=23 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=23 cterm=NONE
  hi Conceal ctermfg=152 ctermbg=23 cterm=NONE
  hi Cursor ctermfg=231 ctermbg=23 cterm=NONE
  hi CursorColumn ctermfg=231 ctermbg=23 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=23 cterm=NONE
  hi CursorLineNr ctermfg=231 ctermbg=23 cterm=bold
  hi DiffAdd ctermfg=231 ctermbg=23 cterm=reverse
  hi DiffChange ctermfg=231 ctermbg=23 cterm=reverse
  hi DiffDelete ctermfg=231 ctermbg=23 cterm=reverse
  hi DiffText ctermfg=231 ctermbg=23 cterm=bold,reverse
  hi Directory ctermfg=231 ctermbg=23 cterm=NONE
  hi EndOfBuffer ctermfg=231 ctermbg=23 cterm=NONE
  hi ErrorMsg ctermfg=231 ctermbg=23 cterm=reverse
  hi FoldColumn ctermfg=231 ctermbg=23 cterm=NONE
  hi Folded ctermfg=214 ctermbg=23 cterm=NONE
  hi IncSearch ctermfg=231 ctermbg=23 cterm=reverse
  hi LineNr ctermfg=152 ctermbg=23 cterm=NONE
  hi MatchParen ctermfg=231 ctermbg=23 cterm=NONE
  hi ModeMsg ctermfg=231 ctermbg=23 cterm=NONE
  hi MoreMsg ctermfg=231 ctermbg=23 cterm=NONE
  hi NonText ctermfg=231 ctermbg=23 cterm=NONE
  hi Pmenu ctermfg=152 ctermbg=23 cterm=NONE
  hi PmenuSbar ctermfg=231 ctermbg=23 cterm=NONE
  hi PmenuSel ctermfg=23 ctermbg=152 cterm=NONE
  hi PmenuThumb ctermfg=231 ctermbg=23 cterm=NONE
  hi Question ctermfg=231 ctermbg=23 cterm=NONE
  hi Search ctermfg=231 ctermbg=23 cterm=NONE
  hi SignColumn ctermfg=231 ctermbg=23 cterm=NONE
  hi SpecialKey ctermfg=231 ctermbg=23 cterm=NONE
  hi SpellBad ctermfg=231 ctermbg=23 cterm=NONE
  hi SpellCap ctermfg=231 ctermbg=23 cterm=NONE
  hi SpellLocal ctermfg=231 ctermbg=23 cterm=NONE
  hi SpellRare ctermfg=231 ctermbg=23 cterm=reverse
  hi StatusLine ctermfg=23 ctermbg=152 cterm=NONE
  hi StatusLineNC ctermfg=23 ctermbg=23 cterm=NONE
  hi TabLine ctermfg=231 ctermbg=23 cterm=NONE
  hi TabLineFill ctermfg=231 ctermbg=23 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=23 cterm=NONE
  hi Title ctermfg=231 ctermbg=23 cterm=NONE
  hi VertSplit ctermfg=23 ctermbg=23 cterm=NONE
  hi Visual ctermfg=231 ctermbg=23 cterm=NONE
  hi VisualNOS ctermfg=231 ctermbg=23 cterm=NONE
  hi WarningMsg ctermfg=231 ctermbg=23 cterm=NONE
  hi WildMenu ctermfg=231 ctermbg=23 cterm=NONE
  hi Comment ctermfg=152 ctermbg=23 cterm=italic
  hi Constant ctermfg=101 ctermbg=23 cterm=NONE
  hi Error ctermfg=124 ctermbg=23 cterm=bold,underline
  hi Identifier ctermfg=33 ctermbg=23 cterm=NONE
  hi Ignore ctermfg=152 ctermbg=23 cterm=bold
  hi PreProc ctermfg=109 ctermbg=23 cterm=bold
  hi Special ctermfg=160 ctermbg=23 cterm=NONE
  hi Statement ctermfg=38 ctermbg=23 cterm=NONE
  hi Todo ctermfg=214 ctermbg=23 cterm=NONE
  hi Type ctermfg=185 ctermbg=23 cterm=NONE
  hi Underlined ctermfg=231 ctermbg=23 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=23 cterm=NONE
  hi ToolbarButton ctermfg=231 ctermbg=23 cterm=bold
  hi elixirAtom ctermfg=40 ctermbg=NONE cterm=NONE
  hi elixirFunctionCall ctermfg=109 ctermbg=NONE cterm=NONE
  hi elixirOperator ctermfg=33 ctermbg=NONE cterm=NONE
  hi elixirAlias ctermfg=231 ctermbg=NONE cterm=NONE
  hi elixirTupleDelimiter ctermfg=170 ctermbg=NONE cterm=NONE
  hi elixirStringDelimiter ctermfg=101 ctermbg=NONE cterm=NONE
  hi vimcontinue ctermfg=170 ctermbg=NONE cterm=NONE
  hi vimparensep ctermfg=170 ctermbg=NONE cterm=NONE
  hi vimsep ctermfg=170 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: dark_red       #A64A2E           ~                 DarkRed
" Color: bright_red     #D74200           ~                 LightRed
" Color: dark_orange    #F15F22           ~                 DarkRed
" Color: bright_orange  #E99F10           ~                 LightRed
" Color: brown          #98875F           ~                 DarkYellow
" Color: yellow         #CFC041           ~                 LightYellow
" Color: dark_green     #009403           ~                 DarkGreen
" Color: bright_green   #00C420           ~                 LightGreen
" Color: dark_blue      #0048BD           ~                 DarkBlue
" Color: bright_blue    #0096FF           ~                 LightBlue
" Color: dark_cyan      #40A4B9           ~                 DarkCyan
" Color: bright_cyan    #77BFCF           ~                 LightCyan
" Color: dark_magenta   #B154CF           ~                 DarkMagenta
" Color: bright_magenta #DA5BD6           ~                 LightMagenta
" Color: black          #0F3B3A           ~                 Black
" Color: dark_grey      #155352           ~                 DarkGrey
" Color: bright_grey    #B1C9C3           ~                 LightGrey
" Color: white          #FFFFFF           ~                 White
" Term colors: black bright_red bright_green yellow bright_blue bright_magenta bright_cyan white
" Term colors: black bright_red bright_green yellow
" Term colors: bright_blue bright_magenta bright_cyan white
" vim: et ts=2 sw=2
